---
title: "Lahaina Fire Analysis"
author: "D. Nākoa Farrant"
date: "2023-09-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse) # a suite of packages for data wrangling
library(ggpubr) # aesthetics for publishable figures
library(lemon) # aesthetics for plot axes
library(extrafont) # include Helvetica font
library(lubridate) # useful functions for columns that contain dates
library(here) # for ease of referencing file directories
```

# Figure 1A: Trends in Agriculture in Hawaiʻi from 1898 to 2020
```{r}
ag_AllHI_df <- read.csv(here("data/fig1a_agriculture_AllHI.csv"))

ag_AllHI_df <- ag_AllHI_df %>% 
  mutate(Crop_Factor = factor(Crop, levels = c("Total_Crops", "Sugarcane", "Pineapple", "Pasture")))
```

```{r}
fig1_a <-  ggplot(data = ag_AllHI_df, aes(x = Year, y = Hectares/1e5, color = Crop_Factor, fill = Crop_Factor)) +
  geom_line(linetype = "dashed", aes(color = Crop_Factor), size = 0.3) +
  geom_point(aes(color = Crop_Factor, fill=Crop_Factor, shape = Crop_Factor), size=0.8) +
  scale_color_manual(values = c("Total_Crops" = "purple",
                                "Pasture" = "#bac6a8",
                                "Pineapple" = "#f79e16",
                                "Sugarcane" = "#eb6f6e"), labels = c("Sugarcane" = "Sugar", "Total_Crops" = "Total Crops")) +
scale_fill_manual(values = c("Total_Crops" = "purple",
                                "Pasture" = "#bac6a8",
                                "Pineapple" = "#f79e16",
                                "Sugarcane" = "#eb6f6e",
                              "Total_Crops"), labels = c("Sugarcane" = "Sugar", "Total_Crops" = "Total Crops")) +
  scale_shape_manual(values = c("Total_Crops" = 23,
                                "Pasture" = 21,
                                "Pineapple" = 2,
                                "Sugarcane" = 21), labels = c("Sugarcane" = "Sugar", "Total_Crops" = "Total Crops")) +
 labs(x = NULL, y = expression(paste("Area cultivated (", 10^{5}, " ha)")), title = NULL, color = NULL, fill = NULL, shape = NULL, tag = "A") +
  scale_x_continuous(breaks = c(1898, 1940, 1980, 2023), limits = c(1898, 2023)) +
scale_y_continuous(limits = c(0, 9), breaks = c(0, 3, 6, 9)) +
  theme_pubr() +
  theme(plot.title = element_text(family =  "Helvetica"),
        text = element_text(size = 7, color = "black"),
        axis.text = element_text(size = 7, color = "black"),
        axis.text.x = element_text(colour="black"), 
        axis.text.y=element_text(margin=margin(r=2), colour="black"),
        axis.ticks = element_line(colour="black", lineend = "square"),
        axis.ticks.length=unit(.1, "cm"),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        legend.key.height= unit(0.18, 'cm'),
           legend.key.width= unit(0.2, 'cm'),
        legend.text = element_text(margin = margin(t = 0, r= 0, b = 0, l = 0)),
    legend.background = element_blank(),
    legend.direction = "vertical",
    legend.position= c(0.83, 0.77),
    plot.tag.position = c(0.3, 0.9),
    plot.tag = element_text(face = "bold", size = 10)
)  +
  guides(fill = guide_legend(byrow = TRUE)) + lemon::coord_capped_cart(bottom = 'both', left = 'both')

fig1_a
```
# Figure 1B: Trends in burned area in Hawaiʻi from 1900 to 2022
```{r}
burned_area_AllHI_df <- read.csv(here("data/fig1b_burned_area_AllHI.csv"))
```


```{r}
fig1_b <-  ggplot(data = burned_area_AllHI_df, aes(x = Year, y = BurnedHectares/1e4)) +
  geom_line(linetype = "solid", color = "black", size = 0.3) +
 labs(x = NULL, y = expression(paste("Burned Area (", 10^{4}, " ha)")), title = NULL, color = NULL, fill = NULL, shape = NULL, tag = "B") +
  scale_x_continuous(breaks = c(1898, 1940, 1980, 2023), limits = c(1898, 2023)) +
scale_y_continuous(limits = c(0, 2), breaks = c(0, 1, 2)) +
  theme_pubr() +
  theme(plot.title = element_text(family =  "Helvetica"),
        text = element_text(size = 7, color = "black"),
        axis.text = element_text(size = 7, color = "black"),
        axis.text.x = element_text(colour="black"), 
        axis.text.y=element_text(margin=margin(r=2), colour="black"),
        axis.ticks = element_line(colour="black", lineend = "square"),
        axis.ticks.length=unit(.1, "cm"),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        legend.key.height= unit(0.1, 'cm'),
           legend.key.width= unit(0.2, 'cm'),
        legend.text = element_text(margin = margin(t = 0, r= 0, b = 0, l = 0)),
    legend.background = element_blank(),
    legend.direction = "vertical",
    legend.position= c(0.3, 0.5),
    plot.tag.position = c(0.3, 0.9),
    plot.tag = element_text(face = "bold", size = 10)
)  +
  guides(fill = guide_legend(byrow = TRUE)) + lemon::coord_capped_cart(bottom = 'both', left = 'both')

fig1_b
```

# Figure 1C: Trends in burned area across agricultural lands in Hawaiʻi from 1999 to 2022
```{r}
burned_landcover_AllHI_df <- read.csv(here("data/fig1c_burned_landcover_AllHI.csv"))

burned_landcover_AllHI_df <- burned_landcover_AllHI_df %>% 
  mutate(LandCover_factor = factor(LandCover, levels = c( "Pasture", "Pineapple", "Sugar", "Other")))
```

```{r}
fig1_c <-  ggplot(burned_landcover_AllHI_df, aes(x = Year, y = BurnedHectares/1e4)) +
 geom_col(aes(fill = forcats::fct_rev(LandCover_factor))) +
scale_fill_manual(values = c("Other" = "#6a6162",
                                "Pasture" = "#bac6a8",
                                "Pineapple" = "#f79e16",
                                "Sugar" = "#eb6f6e")) +
 labs(x = NULL, y = expression(paste("Burned area (", 10^{4}, " ha)")), title = NULL, color = NULL, fill = NULL, shape = NULL, tag = "C") +
 scale_x_continuous(breaks = seq(1999, 2023, by = 8)) +
scale_y_continuous(limits = c(0, 2), breaks = c(0, 1, 2)) +
  theme_pubr() +
  theme(plot.title = element_text(family =  "Helvetica"),
        text = element_text(size = 7, color = "black"),
        axis.text = element_text(size = 7, color = "black"),
        axis.text.x = element_text(colour="black"), 
        axis.text.y=element_text(margin=margin(r=2), colour="black"),
        axis.ticks = element_line(colour="black", lineend = "square"),
        axis.ticks.length=unit(.1, "cm"),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        legend.key.height= unit(0.1, 'cm'),
           legend.key.width= unit(0.2, 'cm'),
        legend.text = element_text(margin = margin(t = 0, r= 0, b = 0, l = 0)),
    legend.background = element_blank(),
    legend.direction = "vertical",
    legend.position= c(0.6, 0.85),
    #legend.position= c(0.17, 0.8),
    #legend.position= "none",
    plot.tag.position = c(0.17, 0.94),
    plot.tag = element_text(face = "bold", size = 10)
)  +
  guides(fill = guide_legend(byrow = TRUE)) + lemon::coord_capped_cart(bottom = 'both', left = 'both')

fig1_c
```
# Figure 2A: Trends in burned area across agricultural lands in West Maui from 1999 to 2022
```{r}
burned_landcover_WestMaui_df <- read.csv(here("data/fig2a_burned_landcover_WestMaui.csv"))

burned_landcover_WestMaui_df <- burned_landcover_WestMaui_df %>% 
  mutate(LandCover_factor = factor(LandCover, levels = c( "Pasture", "Pineapple", "Sugar", "Other")))
```

```{r}

fig2a <-  ggplot(burned_landcover_WestMaui_df, aes(x = Year, y = BurnedHectares/1e3)) +
 geom_col(aes(fill = forcats::fct_rev(LandCover_factor))) +
scale_fill_manual(values = c("Other" = "#6a6162",
                                "Pasture" = "#bac6a8",
                                "Pineapple" = "#f79e16",
                                "Sugar" = "#eb6f6e"), labels = c(
                                "Pineapple" = "Pineapple")) +
 labs(x = NULL, y = expression(paste("Burned area (", 10^{3}, " ha)")), title = NULL, color = NULL, fill = NULL, shape = NULL, tag = "A") +
 scale_x_continuous(limits = c(1998, 2024), breaks = seq(1999, 2023, by = 8)) +
scale_y_continuous(limits = c(0, 3), breaks = c(0, 1.5, 3)) +
  theme_pubr() +
  theme(plot.title = element_text(family =  "Helvetica"),
        text = element_text(size = 7, color = "black"),
        axis.text = element_text(size = 7, color = "black"),
        axis.text.x = element_text(colour="black"), 
        axis.text.y=element_text(margin=margin(r=2), colour="black"),
        axis.ticks = element_line(colour="black", lineend = "square"),
        axis.ticks.length=unit(.1, "cm"),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        legend.key.height= unit(0.05, 'cm'),
           legend.key.width= unit(0.2, 'cm'),
        legend.text = element_text(margin = margin(t = 0, r= 0, b = 0, l = 0)),
    #legend.spacing.y = unit(0.1, 'cm'),
    legend.background = element_blank(),
    legend.direction = "vertical",
    legend.position= c(0.18, 0.78),
    plot.tag.position = c(0.93, 0.93),
    plot.tag = element_text(face = "bold", size = 10)
)  +
  guides(fill=guide_legend(byrow=TRUE)) + lemon::coord_capped_cart(bottom = 'both', left = 'both')

fig2a
```

# Figure 2B: Rainfall in West Maui from 1999 to 2022
```{r}
rainfall_WestMaui_df <- read.csv(here("data/fig2b_rainfall_WestMaui.csv"))

rainfall_WestMaui_df <- rainfall_WestMaui_df %>% 
  mutate(YearMonth = as.Date(YearMonth))
```

```{r}
fig2b <- ggplot() + 
  geom_col(data = rainfall_WestMaui_df, aes(x = YearMonth, y = Rain_mm/1e2), col = "lightblue", fill = "lightblue") +
   geom_line(data = rainfall_WestMaui_df, aes(x = YearMonth, y = Rain_mm_1yr/1e2), size = 0.3) +
  scale_color_manual(values = c("Rain_mm_1yr" = "navy"), labels = c("Rain_mm_1yr" = "12-month rolling mean")) +
labs(x = NULL, y = expression(paste("Monthly rainfall (", 10^{2}, " mm)")), title = NULL, color = NULL, fill = NULL, shape = NULL, tag = "B") +
  scale_x_date(limits = c(as.Date("1998-12-01", "%Y-%m-%d"), as.Date("2024-01-01", "%Y-%m-%d")), breaks = as.Date(c("1999-06-01", "2007-06-01", "2015-06-01", "2023-06-01")), date_labels = "%Y") +
#scale_y_continuous(limits = c(0, 2.6), breaks = c(0, 1.3, 2.6)) +
  theme_pubr() +
  theme(plot.title = element_text(family =  "Helvetica"),
        text = element_text(size = 7, color = "black"),
        axis.text = element_text(size = 7, color = "black"),
        axis.text.x = element_text(colour="black"), 
        axis.text.y=element_text(margin=margin(r=2), colour="black"),
        axis.ticks = element_line(colour="black", lineend = "square"),
        axis.ticks.length=unit(.1, "cm"),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        legend.key.height= unit(0.05, 'cm'),
           legend.key.width= unit(0.2, 'cm'),
        legend.text = element_text(margin = margin(t = 0, r= 0, b = 0, l = 0)),
    legend.background = element_blank(),
    legend.direction = "vertical",
    legend.position= c(0.68, 0.8),
    plot.tag.position = c(0.93, 0.93),
    plot.tag = element_text(face = "bold", size = 10)
)  +
  guides(fill=guide_legend(nrow=2,byrow=TRUE)) + lemon::coord_capped_cart(bottom = 'both', left = 'both')

fig2b
```